### ISSUE TITLE
nested structures

### ISSUE THREAD

**Issue by zeratax** [icyleaf/swagger#17]
Hey thank you so much for this project!

I am currently trying to define arrays of custom types as properties and I'm not exactly sure how that works? 

So far I am getting the impression that I can only reference other objects for responses, but nothing else.

I have an object called `Songs` and I want to have an object called `Queue` that's just an array of songs

```crystal 
builder.add(Swagger::Object.new("Song", "object", [
  Swagger::Property.new("id", "string"),
  Swagger::Property.new("name", "string"),
  Swagger::Property.new("artist", "string"),
  Swagger::Property.new("image", "string"),
  Swagger::Property.new("length", "integer"),
]))

builder.add(Swagger::Object.new("Queue", "object", [
  Swagger::Property.new("songs", "array"),
]))
```

but instead of array I really want to have something like array[Song]. In general the examples don't seem to go over any kind of nesting so I'm having trouble conceptualising how I would go about this.

**Comment by icyleaf** [comment]
Swagger is still in early stage which most properties need hard code String value to render, you can try:

```crystal
builder.add(Swagger::Object.new("Song", "object", [
  Swagger::Property.new("id", "string"),
  Swagger::Property.new("name", "string"),
  Swagger::Property.new("artist", "string"),
  Swagger::Property.new("image", "string"),
  Swagger::Property.new("length", "integer"),
]))

builder.add(Swagger::Object.new("Queue", "object", [
  Swagger::Property.new("songs", "Array(Song)")
]))
```

But can be not assign the example code, Swagger do not support `Array` or `Hash`.

**Comment by icyleaf** [comment]
Close for now, feel free to reopen it.
