### ISSUE TITLE
Use git submodule/subtree for Swagger UI?

### ISSUE THREAD

**Issue by j8r** [icyleaf/swagger#6]
[Swagger UI](https://github.com/swagger-api/swagger-ui) is an entirely other project than this Crystal onel.
It would be better to use git module/subtree to easily update the files, instead of vendoring the JS/CSS files. It would also keep the history.

In my opinion, the whole Swagger HTTP server can even be an new Crystal project, based on this shard (but I agree it can be practical to have it here).

**Comment by j8r** [comment]
The "damage" is done, having this assets in this repos make it weight a lot more that only Crystal source code. 

In fact @icyleaf , it isn't even needed to have them: we can use the resources form https://petstore.swagger.io/ like https://petstore.swagger.io/swagger-ui-bundle.js and https://petstore.swagger.io/swagger-ui.css

**Comment by j8r** [comment]
The "damage" is done, having this assets in this repos make it weight a lot more that only Crystal source code. 

In fact @icyleaf , it isn't even needed to have them: we can use the resources from https://petstore.swagger.io/ like https://petstore.swagger.io/swagger-ui-bundle.js and https://petstore.swagger.io/swagger-ui.css

**Comment by icyleaf** [comment]
I am working on it by using jsdelivr cdn source.

**Comment by j8r** [comment]
@icyleaf  I just noticied there is an official unpkg available: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md#unpkg

**Comment by icyleaf** [comment]
jsDelivr has global CDN networks include China.
